apiVersion: apps/v1
kind: Deployment
metadata:
  name: base-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: base
  template:
    metadata:
      labels:
        app: base
    spec:
      containers:
        - name: base
          image: vbox45/base
                   
---
apiVersion: v1
kind: Service
metadata:
  name: base-srv
spec:
  selector:
    app: base
  ports:
    - name: base
      protocol: TCP
      port: 9000
      targetPort: 9000
      
      
      
      
      
      
